name: aldeewan_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.6.1
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  path_provider: ^2.1.2
  go_router: ^17.0.0
  lucide_icons: ^0.257.0
  uuid: ^4.3.3
  url_launcher: ^6.2.5
  realm: ^20.2.0
  google_fonts: ^6.3.2
  fl_chart: ^0.69.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.3.0
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^3.0.1

  flutter_animate: ^4.5.2
  audioplayers: ^6.5.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.13
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/audio/
    - assets/animations/
